apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
  labels:
    app:
spec:
  replicas: 1
  template:
    metadata:
      name:springboot
      labels:
        app:
    spec:
      containers:
        - name:springboot
          image:/springboot:V1
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app:
